modLoader="kotlinforforge"
loaderVersion="[4,)"

issueTrackerURL="https://github.com/SirEdvin/Turtlematic/issues"
logoFile="pack.png"

license="MIT"

[[mods]]
modId="turtlematic"
version="${file.jarVersion}"
displayName="Turtlematic"
displayURL="https://github.com/SirEdvin/Turtlematic/"

credits=""
authors=""
description='''
'''

[[dependencies.turtlematic]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},48)"
ordering="NONE"
side="BOTH"

[[dependencies.turtlematic]]
modId="computercraft"
mandatory=true
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.turtlematic]]
modId="peripheralium"
mandatory=true
versionRange="[${peripheraliumVersion},)"
ordering="NONE"
side="BOTH"